export interface CheapMealSpot {
  id: string;
  name: string;
  spotName: string;
  campusArea: string;
  campusId: string;
  priceMYR: number;
  priceCategory: "under5" | "under8" | "under10";
  category: "Economy Rice & Nasi Campur" | "Nasi Lemak & Ayam" | "Noodles & Soup" | "Mamak & Roti" | "Western & Budget Sets" | "Vegetarian & Healthy";
  estimatedKcal: number;
  proteinGrams: number;
  carbsGrams: number;
  fatGrams: number;
  diet: "Halal" | "Vegetarian" | "Muslim-Friendly" | "Non-Halal";
  distanceToStation: string;
  studentHack: string;
  openingHours: string;
  rating: number;
}

export const CHEAP_CAMPUS_MEALS: CheapMealSpot[] = [
  {
    id: "um-kk12-campur",
    name: "Nasi Campur (Ayam Goreng Berempah + Sayur Kangkung + Kuah Campur)",
    spotName: "Kafeteria Kolej Kediaman 12 (KK12 / KK8)",
    campusArea: "Universiti Malaya (UM)",
    campusId: "um",
    priceMYR: 6.50,
    priceCategory: "under8",
    category: "Economy Rice & Nasi Campur",
    estimatedKcal: 580,
    proteinGrams: 32,
    carbsGrams: 65,
    fatGrams: 19,
    diet: "Halal",
    distanceToStation: "Inside UM Campus (UM Feeder Bus to KJ19 Universiti LRT)",
    studentHack: "Ask for 'kuah banjir kari campur kicap' at zero extra charge. Take 1 protein + 1 vege to stay strictly under RM7.00.",
    openingHours: "7:00 AM – 8:30 PM",
    rating: 4.9
  },
  {
    id: "um-kk10-roti-canai",
    name: "2 Roti Canai Garing with Dhal & Sambal",
    spotName: "KK10 Cafeteria / Dewan Selera UM",
    campusArea: "Universiti Malaya (UM)",
    campusId: "um",
    priceMYR: 3.20,
    priceCategory: "under5",
    category: "Mamak & Roti",
    estimatedKcal: 520,
    proteinGrams: 12,
    carbsGrams: 74,
    fatGrams: 19,
    diet: "Halal",
    distanceToStation: "5 mins from KJ19 Universiti LRT station",
    studentHack: "Pair with plain warm water to keep breakfast spend under RM3.50 total.",
    openingHours: "6:30 AM – 11:00 PM",
    rating: 4.8
  },
  {
    id: "um-banmian-kk3",
    name: "Sup Ban Mian Sup Sayur Manis + Telur",
    spotName: "Kolej Kediaman Ke-3 (KK3) Food Stalls",
    campusArea: "Universiti Malaya (UM)",
    campusId: "um",
    priceMYR: 6.00,
    priceCategory: "under8",
    category: "Noodles & Soup",
    estimatedKcal: 460,
    proteinGrams: 22,
    carbsGrams: 66,
    fatGrams: 11,
    diet: "Halal",
    distanceToStation: "Inside UM Campus / PJ Seksyen 17",
    studentHack: "The broth is light on oil and hydrating for long afternoon revision sessions.",
    openingHours: "8:00 AM – 7:00 PM",
    rating: 4.7
  },
  {
    id: "sunway-rock-economy",
    name: "3-Dish Chinese Economy Rice (Steamed Egg, Tofu & Stir-fry Choy Sum)",
    spotName: "Rock Cafe / Sunway Food Court",
    campusArea: "Sunway / Monash (Bandar Sunway)",
    campusId: "sunway",
    priceMYR: 6.00,
    priceCategory: "under8",
    category: "Economy Rice & Nasi Campur",
    estimatedKcal: 490,
    proteinGrams: 22,
    carbsGrams: 58,
    fatGrams: 14,
    diet: "Non-Halal",
    distanceToStation: "5 mins walk from SB4 SunMed BRT / Canopy Walk",
    studentHack: "Choose steamed minced pork egg or tofu as your protein — it's RM1.50 cheaper than whole drumstick and packs 20g+ protein.",
    openingHours: "10:00 AM – 9:30 PM",
    rating: 4.8
  },
  {
    id: "monash-cafeteria-chickenrice",
    name: "Roasted Chicken Rice with Clear Soup & Cucumber",
    spotName: "Monash Student Cafeteria (Building 6)",
    campusArea: "Monash University Malaysia",
    campusId: "monash",
    priceMYR: 7.50,
    priceCategory: "under8",
    category: "Nasi Lemak & Ayam",
    estimatedKcal: 620,
    proteinGrams: 30,
    carbsGrams: 75,
    fatGrams: 21,
    diet: "Halal",
    distanceToStation: "Direct at Monash Campus / SB5 SunU-Monash BRT",
    studentHack: "Ask for breast meat (isi dada) for maximum lean protein with minimal oil.",
    openingHours: "8:00 AM – 6:00 PM",
    rating: 4.7
  },
  {
    id: "sunway-canopy-sub-vege",
    name: "Vegetarian Economy Rice (3 Veg + Fried Tempeh)",
    spotName: "Sunway Waterfront Food Street",
    campusArea: "Sunway / Monash (Bandar Sunway)",
    campusId: "sunway",
    priceMYR: 5.80,
    priceCategory: "under8",
    category: "Vegetarian & Healthy",
    estimatedKcal: 430,
    proteinGrams: 19,
    carbsGrams: 64,
    fatGrams: 11,
    diet: "Vegetarian",
    distanceToStation: "3 mins from SB4 SunMed BRT station",
    studentHack: "Tempeh gives high clean plant protein and prebiotics without high cost.",
    openingHours: "9:00 AM – 8:00 PM",
    rating: 4.8
  },
  {
    id: "mamak-roti-telur-set",
    name: "Roti Canai (2 Pcs) with Dhal & Spicy Sambal",
    spotName: "Restoran Al-Fariz Maju / Syed Bistro",
    campusArea: "PJ Seksyen 14 / Bangsar / All Campuses",
    campusId: "all",
    priceMYR: 3.60,
    priceCategory: "under5",
    category: "Mamak & Roti",
    estimatedKcal: 560,
    proteinGrams: 14,
    carbsGrams: 78,
    fatGrams: 22,
    diet: "Halal",
    distanceToStation: "Near most LRT stations (Pasar Seni, Universiti, SS15)",
    studentHack: "Cheapest breakfast in Malaysia. Ask for 'kuah dhal asing' so it doesn't get soggy.",
    openingHours: "24 Hours",
    rating: 4.8
  },
  {
    id: "ss15-ban-mian",
    name: "Traditional Hand-pulled Soup Ban Mian (Minced Meat + Sayur Manis + Ikan Bilis)",
    spotName: "Restoran Super Kitchen / SS15 Noodle Stalls",
    campusArea: "Taylor's / INTI / SS15 Subang",
    campusId: "taylors",
    priceMYR: 7.80,
    priceCategory: "under8",
    category: "Noodles & Soup",
    estimatedKcal: 510,
    proteinGrams: 24,
    carbsGrams: 72,
    fatGrams: 12,
    diet: "Non-Halal",
    distanceToStation: "4 mins walk from KJ20 SS15 LRT",
    studentHack: "Soup version is significantly lower in calories and sodium compared to dry chili oil version.",
    openingHours: "9:00 AM – 9:00 PM",
    rating: 4.7
  },
  {
    id: "ss15-student-spaghetti",
    name: "Creamy Carbonara with Grilled Chicken Slices (Student Lunch Deal)",
    spotName: "Big Hug / Subang SS15 Cafe",
    campusArea: "Taylor's / Sunway / SS15",
    campusId: "taylors",
    priceMYR: 9.90,
    priceCategory: "under10",
    category: "Western & Budget Sets",
    estimatedKcal: 640,
    proteinGrams: 28,
    carbsGrams: 76,
    fatGrams: 22,
    diet: "Muslim-Friendly",
    distanceToStation: "5 mins from KJ20 SS15 LRT",
    studentHack: "Show student ID card to get free iced lemon tea upgrade on weekdays 11am-3pm.",
    openingHours: "11:00 AM – 9:00 PM",
    rating: 4.6
  },
  {
    id: "taylors-lakeside-nasi-ayam",
    name: "Nasi Ayam Hainan Steamed Chicken Set",
    spotName: "Syopz Mall Food Court / Lakeside Campus",
    campusArea: "Taylor's University Lakeside Campus",
    campusId: "taylors",
    priceMYR: 8.50,
    priceCategory: "under10",
    category: "Nasi Lemak & Ayam",
    estimatedKcal: 590,
    proteinGrams: 31,
    carbsGrams: 72,
    fatGrams: 17,
    diet: "Halal",
    distanceToStation: "Taylor's Shuttle Bus from KJ20 SS15 LRT",
    studentHack: "Ask for extra cucumber and steamed breast meat for optimal protein-to-fat balance.",
    openingHours: "9:00 AM – 6:30 PM",
    rating: 4.7
  },
  {
    id: "apu-bukit-jalil-chapati",
    name: "2 Fresh Hot Chapatis with Yellow Dhal & Mint Chutney",
    spotName: "Restoran Mahbub / Bukit Jalil Mamak Corner",
    campusArea: "APU (Bukit Jalil / Sri Petaling)",
    campusId: "apu",
    priceMYR: 4.20,
    priceCategory: "under5",
    category: "Mamak & Roti",
    estimatedKcal: 380,
    proteinGrams: 12,
    carbsGrams: 64,
    fatGrams: 6,
    diet: "Halal",
    distanceToStation: "7 mins walk from SP18 Bukit Jalil LRT / APU Shuttle Bus",
    studentHack: "Chapati uses zero oil during pan frying, making it 50% lower in fat than Roti Canai with equal energy.",
    openingHours: "7:00 AM – 11:00 PM",
    rating: 4.9
  },
  {
    id: "apu-cafeteria-mixed-rice",
    name: "Nasi Campur (Ayam Kunyit + Kobis Goreng + Kuah Kari)",
    spotName: "APU Campus Cafeteria Block B",
    campusArea: "APU (Bukit Jalil / Sri Petaling)",
    campusId: "apu",
    priceMYR: 6.80,
    priceCategory: "under8",
    category: "Economy Rice & Nasi Campur",
    estimatedKcal: 570,
    proteinGrams: 28,
    carbsGrams: 68,
    fatGrams: 18,
    diet: "Halal",
    distanceToStation: "Direct APU Campus Shuttle to SP18 Bukit Jalil LRT",
    studentHack: "Add free soup and ask for kari dhal on rice for maximum flavor.",
    openingHours: "7:30 AM – 7:30 PM",
    rating: 4.8
  },
  {
    id: "ukm-pusat-islam-ayam-gepuk",
    name: "Ayam Gepuk Set (Rice + Sambal Bilis + Fried Tofu + Tempeh)",
    spotName: "Pusanika Food Court / Kompleks UKM",
    campusArea: "Universiti Kebangsaan Malaysia (UKM Bangi)",
    campusId: "ukm",
    priceMYR: 7.00,
    priceCategory: "under8",
    category: "Nasi Lemak & Ayam",
    estimatedKcal: 690,
    proteinGrams: 35,
    carbsGrams: 70,
    fatGrams: 26,
    diet: "Halal",
    distanceToStation: "Inside UKM Campus / UKM Feeder Bus to KB06 UKM KTM",
    studentHack: "Tempeh and tofu add 12g of clean plant protein for under RM1.50.",
    openingHours: "9:00 AM – 8:00 PM",
    rating: 4.8
  },
  {
    id: "ukm-bangi-mee-sup",
    name: "Kuey Teow Sup Daging & Sayur Sawi",
    spotName: "Kafeteria Kolej Ibrahim Yaakob (KIY UKM)",
    campusArea: "Universiti Kebangsaan Malaysia (UKM Bangi)",
    campusId: "ukm",
    priceMYR: 6.20,
    priceCategory: "under8",
    category: "Noodles & Soup",
    estimatedKcal: 480,
    proteinGrams: 27,
    carbsGrams: 62,
    fatGrams: 13,
    diet: "Halal",
    distanceToStation: "Feeder Bus to KB06 UKM KTM Station",
    studentHack: "Beef broth is rich in iron, zinc, and bioavailable protein for exam prep.",
    openingHours: "8:00 AM – 9:00 PM",
    rating: 4.7
  },
  {
    id: "uitm-shah-alam-nasi-kukus",
    name: "Nasi Kukus Ayam Berempah dengan Kuah Gulai & Sambal Belacan",
    spotName: "Medan Selera Seksyen 7 / Restoran Hakim",
    campusArea: "UiTM Shah Alam",
    campusId: "uitm",
    priceMYR: 7.50,
    priceCategory: "under8",
    category: "Nasi Lemak & Ayam",
    estimatedKcal: 680,
    proteinGrams: 36,
    carbsGrams: 74,
    fatGrams: 24,
    diet: "Halal",
    distanceToStation: "Near KD11 Padang Jawa KTM / RapidKL Bus 708",
    studentHack: "Huge portion that easily powers a full afternoon of lab lectures. Ask for less oil on chicken.",
    openingHours: "10:00 AM – 11:00 PM",
    rating: 4.8
  },
  {
    id: "uitm-shah-alam-roti-john",
    name: "Roti John Ayam Mini with Salad & Black Pepper Sauce",
    spotName: "Food Court Seksyen 2 / Pusat Komersial UiTM",
    campusArea: "UiTM Shah Alam",
    campusId: "uitm",
    priceMYR: 5.00,
    priceCategory: "under5",
    category: "Western & Budget Sets",
    estimatedKcal: 490,
    proteinGrams: 24,
    carbsGrams: 52,
    fatGrams: 20,
    diet: "Halal",
    distanceToStation: "10 mins from KD11 Padang Jawa KTM",
    studentHack: "Great value supper snack that provides substantial protein under RM5.",
    openingHours: "4:00 PM – 12:00 AM",
    rating: 4.7
  },
  {
    id: "tarumt-setapak-vege-rice",
    name: "4-Dish Vegetarian Mixed Rice (Brown Rice, Tofu, Broccoli & Pumpkin)",
    spotName: "Setapak Vegetarian Oasis / TAR UMT Food Stalls",
    campusArea: "TAR UMT (Setapak / Wangsa Maju)",
    campusId: "tarumt",
    priceMYR: 5.50,
    priceCategory: "under8",
    category: "Vegetarian & Healthy",
    estimatedKcal: 440,
    proteinGrams: 18,
    carbsGrams: 68,
    fatGrams: 9,
    diet: "Vegetarian",
    distanceToStation: "8 mins walk from KJ3 Wangsa Maju LRT",
    studentHack: "Full nutrition with micro-nutrients. Free Chinese herbal soup refill included with every meal.",
    openingHours: "9:30 AM – 7:30 PM",
    rating: 4.9
  },
  {
    id: "tarumt-chicken-chop-rice",
    name: "Fried Chicken Chop Rice with Onion Gravy",
    spotName: "Prima Setapak Food Court",
    campusArea: "TAR UMT (Setapak / Wangsa Maju)",
    campusId: "tarumt",
    priceMYR: 8.00,
    priceCategory: "under8",
    category: "Western & Budget Sets",
    estimatedKcal: 720,
    proteinGrams: 32,
    carbsGrams: 80,
    fatGrams: 28,
    diet: "Non-Halal",
    distanceToStation: "Feeder bus from KJ3 Wangsa Maju LRT",
    studentHack: "Huge crispy cutlet size that will keep you full until late evening.",
    openingHours: "11:00 AM – 9:00 PM",
    rating: 4.6
  },
  {
    id: "upm-serdang-tomyum",
    name: "Sup Bihun Tom Yum Ayam & Sayur Cendawan",
    spotName: "Kolej 13 / Pasar Malam UPM Flat",
    campusArea: "Universiti Putra Malaysia (UPM Serdang)",
    campusId: "upm",
    priceMYR: 6.80,
    priceCategory: "under8",
    category: "Noodles & Soup",
    estimatedKcal: 460,
    proteinGrams: 26,
    carbsGrams: 60,
    fatGrams: 10,
    diet: "Halal",
    distanceToStation: "Near PY34 UPM MRT Putrajaya Line station",
    studentHack: "High hydration, spicy kick for studying, and packed with lean chicken slices.",
    openingHours: "11:00 AM – 10:00 PM",
    rating: 4.7
  },
  {
    id: "upm-nasi-kerabu",
    name: "Nasi Kerabu Ayam Bakar dengan Ulam-ulaman Segar",
    spotName: "Kafeteria Canselori UPM Serdang",
    campusArea: "Universiti Putra Malaysia (UPM Serdang)",
    campusId: "upm",
    priceMYR: 7.50,
    priceCategory: "under8",
    category: "Nasi Lemak & Ayam",
    estimatedKcal: 560,
    proteinGrams: 34,
    carbsGrams: 68,
    fatGrams: 15,
    diet: "Halal",
    distanceToStation: "UPM Bus to PY34 UPM MRT station",
    studentHack: "Fresh herbs (ulam) provide natural fiber, vitamins, and antioxidants for brain health.",
    openingHours: "8:00 AM – 4:30 PM",
    rating: 4.9
  },
  {
    id: "budget-kopitiam-breakfast",
    name: "Kaya Butter Toast + 2 Half-Boiled Eggs + Kopi O",
    spotName: "Kopitiam Sin Seng Nam / Restoran Yut Kee",
    campusArea: "KL City / Pasar Seni / Central",
    campusId: "all",
    priceMYR: 4.80,
    priceCategory: "under5",
    category: "Mamak & Roti",
    estimatedKcal: 390,
    proteinGrams: 15,
    carbsGrams: 42,
    fatGrams: 17,
    diet: "Muslim-Friendly",
    distanceToStation: "2 mins from KJ14 Pasar Seni LRT / MRT",
    studentHack: "2 half-boiled eggs give 12g of highly bioavailable protein for just RM2.20.",
    openingHours: "7:00 AM – 3:30 PM",
    rating: 4.9
  },
  {
    id: "utar-sg-long-pork-noodles",
    name: "Traditional Minced Pork Soup Noodles with Egg & Veg",
    spotName: "Kedai Kopi Sg Long Food Street",
    campusArea: "UTAR (Sungai Long)",
    campusId: "utar",
    priceMYR: 7.00,
    priceCategory: "under8",
    category: "Noodles & Soup",
    estimatedKcal: 520,
    proteinGrams: 26,
    carbsGrams: 64,
    fatGrams: 16,
    diet: "Non-Halal",
    distanceToStation: "UTAR Shuttle Bus from KG29 Bukit Dukung MRT",
    studentHack: "Add an extra egg (+RM1.20) for 6g extra protein to keep you full through 4-hour lectures.",
    openingHours: "7:30 AM – 4:00 PM",
    rating: 4.7
  },
  {
    id: "utar-sg-long-vege-bento",
    name: "Healthy Vegetarian Bento (Tofu + Long Beans + Sweet Potato)",
    spotName: "Green Leaves Vegetarian / UTAR West Gate",
    campusArea: "UTAR (Sungai Long)",
    campusId: "utar",
    priceMYR: 5.80,
    priceCategory: "under8",
    category: "Vegetarian & Healthy",
    estimatedKcal: 420,
    proteinGrams: 16,
    carbsGrams: 66,
    fatGrams: 10,
    diet: "Vegetarian",
    distanceToStation: "UTAR Shuttle to KG29 Bukit Dukung MRT",
    studentHack: "Sweet potato provides slow-burning complex carbs for sustained afternoon energy.",
    openingHours: "8:00 AM – 8:00 PM",
    rating: 4.8
  },
  {
    id: "mmu-cyberjaya-nasi-kandar",
    name: "Nasi Kandar Student Plate (1 Ayam Goreng + Bendi + Kuah Campur)",
    spotName: "Restoran Cyber Curry House / The Domain",
    campusArea: "MMU (Cyberjaya)",
    campusId: "mmu",
    priceMYR: 8.50,
    priceCategory: "under10",
    category: "Economy Rice & Nasi Campur",
    estimatedKcal: 710,
    proteinGrams: 34,
    carbsGrams: 78,
    fatGrams: 25,
    diet: "Halal",
    distanceToStation: "RapidKL Bus T504 to PY41 Cyberjaya City Centre MRT",
    studentHack: "Avoid taking sotong or udang (squid/prawns) at Mamaks as they will double your bill unexpectedly!",
    openingHours: "24 Hours",
    rating: 4.6
  },
  {
    id: "mmu-cyberjaya-tosai",
    name: "Plain Tosai with Coconut Chutney & Sambar",
    spotName: "Restoran Bismillah / Cyberjaya Corner",
    campusArea: "MMU (Cyberjaya)",
    campusId: "mmu",
    priceMYR: 3.00,
    priceCategory: "under5",
    category: "Mamak & Roti",
    estimatedKcal: 290,
    proteinGrams: 9,
    carbsGrams: 50,
    fatGrams: 5,
    diet: "Halal",
    distanceToStation: "5 mins walk from MMU Gate / Cyberjaya Transit",
    studentHack: "Fermented batter is very easy to digest before early morning exam sessions.",
    openingHours: "24 Hours",
    rating: 4.8
  }
];
